

// <autogenerated>
//   This file was generated by T4 code generator TestComponent.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace OpenAOE.Engine.Data.CodeGeneration
{
	public interface ITestComponent
	{
	}

	public interface IWriteableTestComponent
	{
	}
}